CREATE TABLE STUDY_BOARD (
       STUDYBOARD_ID NUMBER NOT NULL,
       STUDYBOARD_MEMBER_ID VARCHAR2(15) NOT NULL,
       STUDYBOARD_TITLE VARCHAR2(300) NOT NULL,
       STUDYBOARD_CONTENT VARCHAR2(3000) NOT NULL,
       STUDYBOARD_FILENAME VARCHAR2(100),
       STUDYBOARD_WRITE_DT DATE,
       STUDYBOARD_VIEWCOUNT NUMBER(5),
       STUDYBOARD_DELETEYN VARCHAR2(1),

      CONSTRAINT STUDY_BOARD_PK PRIMARY KEY (STUDYBOARD_ID),
      CONSTRAINT MEMBER_FK FOREIGN KEY (STUDYBOARD_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
    
);
