drop TABLE faq CASCADE CONSTRAINTS;
drop TABLE freeboard CASCADE CONSTRAINTS;
drop TABLE freereply CASCADE CONSTRAINTS;
drop table tutor_reject;
drop table reject_category cascade constraints;
drop table member_auth;
drop TABLE lecture CASCADE CONSTRAINTS;
drop TABLE lecture_category CASCADE CONSTRAINTS;
drop TABLE lecture_detail CASCADE CONSTRAINTS;
drop TABLE member CASCADE CONSTRAINTS;
drop TABLE member_lecture_history CASCADE CONSTRAINTS;
drop TABLE review CASCADE CONSTRAINTS;
drop TABLE studyboard CASCADE CONSTRAINTS;
drop TABLE studyreply CASCADE CONSTRAINTS;
drop TABLE tutor CASCADE CONSTRAINTS;
drop TABLE wishlist CASCADE CONSTRAINTS;
