INSERT
INTO lecture(LECTURE_ID, LECTURE_CATEGORY_ID, 
LECTURE_TUTOR_ID, LECTURE_IMG, LECTURE_TITLE, LECTURE_PRICE, LECTURE_STATE, LECTURE_START_DT, LECTURE_END_DT, LECTURE_MAX, LECTURE_MIN, LECTURE_CURRENT)
VALUES(lecture_seq.nextVal, (SELECT category_id
FROM LECTURE_CATEGORY WHERE category_id = 'SP'), 'member2', 'LECTURE_IMG', 'LECTURE_TITLE', 10000, 'STATE', '20/10/10', '20/10/10', 10, 5, 0);

INSERT
INTO lecture_detail(LECTURE_ID, LECTURE_CATEGORY_ID, LECTURE_INTRODUCE, LECTURE_CURRICULUM, LECTURE_PREPARED, LECTURE_CAUTION, LECTURE_FILENAME, LECTURE_REJECT_REASON, LECTURE_CANCEL_REASON, LECTURE_LOCATION)
VALUES(lecture_seq.currval, (SELECT category_id
FROM LECTURE_CATEGORY WHERE category_id = 'SP'), 'LECTURE_INTRODUCE', 'LECTURE_CURRICULUM', 'LECTURE_PREPARED', 'LECTURE_CAUTION', 'LECTURE_FILENAME', 'LECTURE_REJECT_REASON', 'LECTURE_CANCEL_REASON', 'LECTURE_LOCATION');