INSERT
INTO lecture(LECTURE_ID, LECTURE_CATEGORY_ID, 
LECTURE_TUTOR_ID, LECTURE_IMG, LECTURE_TITLE, LECTURE_PRICE, LECTURE_STATE, LECTURE_START_DT, LECTURE_END_DT, LECTURE_MAX, LECTURE_MIN)
VALUES(lecture_seq.nextVal, (SELECT category_id
FROM LECTURE_CATEGORY WHERE category_id = 'SP'), 'member2', 'LECTURE_IMG', 'LECTURE_TITLE', 10000, 'STATE', to_date(sysdate,'yyyy-mm-dd hh24:mi:ss'), '20/10/10', 10, 5);


SELECT VALUE FROM NLS_SESSION_PARAMETERS WHERE PARAMETER = 'NLS_DATE_FORMAT';
 ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd hh24:mi:ss';
INSERT
INTO lecture_detail(LECTURE_ID, LECTURE_CATEGORY_ID, LECTURE_INTRODUCE, LECTURE_CURRICULUM, LECTURE_PREPARED, LECTURE_CAUTION, LECTURE_FILENAME, LECTURE_LOCATION)
VALUES(lecture_seq.currval, (SELECT category_id
FROM LECTURE_CATEGORY WHERE category_id = 'SP'), 'LECTURE_INTRODUCE', 'LECTURE_CURRICULUM', 'LECTURE_PREPARED', 'LECTURE_CAUTION', 'LECTURE_FILENAME', 'LECTURE_LOCATION');


INSERT INTO STUDYREPLY VALUES(STUDYREPLY_SEQ.NEXTVAL, 2, 'member3', '댓글입니다22',sysdate);
commit;